### ISSUE TITLE
Expanding available geographies

### ISSUE THREAD

**Issue by jo-schroeder** [uva-bi-sdad/community#1]
We want to add more geographies (capital region) for mastercard websites. This includes expanding available census boundaries to include MD and DC, as well as new levels like school district or civic association. 
Should all possible geographies always be imported in the package? Should users have a way of importing their own geographies?
How can we adapt the existing hierarchical method of exploring geographies to make sense with new levels?

**Comment by miserman** [comment]
Currently, the shape part of geographies are always just specified with a URL in `output_map`, so as long as they're available somewhere, they can be freely added. The ones in the VDH demo are being served from [docs/dist/shapes](https://github.com/uva-bi-sdad/community/tree/main/docs/dist/shapes), which we could add to. It might also be nice to add a way to include those locally, and either bundle them in the index file or include them in docs (the same way data can be included).

Another part of geographies are the feature files (e.g., [virginia_2010.json](https://github.com/uva-bi-sdad/community/blob/main/docs/dist/shapes/VA/virginia_2010.json)), which is where region names are coming from. We could add the same sort of files for new regions, or include names in the data (though that would require some reworking).

The hierarchical stuff isn't hard-coded (all currently specified with `input_variable`s), but new functionality might need to be added to accommodate new methods. It would probably be nice to at least add multiple region selection.
