### ISSUE TITLE
Search with built in constraints

### ISSUE THREAD

**Issue by wanghalan** [uva-bi-sdad/community#34]
It is possible to change the queries and result in empty data views. Would it be possible to change this, so combinations that lead to empty data views are impossible to select? 

One strategy can be a "left-to-right" approach, where the layering can be Selected years --> District --> County --> Region Types --> variables. For example, changing the information upstream resets downstream selections _if_ they do not exist.

**Comment by miserman** [comment]
This is maybe the same as #14 with added consideration of the global filter, which doesn't currently support feature filtering (like entity IDs and features from entity info like region types).

Parts of this already exists for select-like inputs:
- One is for `options = "ids"`, where the `subset` defines the set of IDs to display. A similar mechanism could be applied to filter variables, but it would need to check the selection-specific summary of each variable.
- Another is for  `options = "variables"`, where `group_feature` can make the set of displayed variables dependent on another input.

Those cases are both with data-derived option sets, but it gets trickier with user-specified option sets that are then used to filter data. For those, there would need to be some mechanism to associate the provided options with whatever they're filtering.

Another part that already exists is for display conditions on inputs (like those specified through [page_sections](https://uva-bi-sdad.github.io/community/reference/page_section.html)), where the input is cleared when hidden. These can only currently be conditioned on other inputs, but could potentially be expanded to condition on aspects of the dataview.

For the global filter specifically, it might make sense to automatically disable conditions that result in no data, but they should probably still be specifiable, especially considering they can be specified through the URL.

A general concern is that it might be annoying if selections get cleared unexpectedly.

**Comment by wanghalan** [comment]
When I think more deeply about it, it might be sufficient that there is feedback (i.e., lighter colors/ separate colors) for selections that, if all other variables are held equal, results in no data? For example, arrows for the year selector, county, or variable can be grayed out if selecting it leads to no data. In this way, no inputs need to be cleared, but users will not have to click on the item to see that information does not exist. The main issue I see is that this might be difficult to implement. For instance, there might need to be a routine that calculates valid queries. Which file/lines do you recommend I might look towards to tackle this?

**Comment by wanghalan** [comment]
Closed by #38
