### ISSUE TITLE
Demographics not loading for Arlington Neighborhoods

### ISSUE THREAD

**Issue by dads2busy** [uva-bi-sdad/community#9]
Demographics have stopped loading for Arlington Neighborhoods. Maybe associated with updated data including hispanic?

**Comment by jo-schroeder** [comment]
The neighborhood demographic data are stored in a different repo than the ACS. I think @miserman did something before to reconcile this

**Comment by miserman** [comment]
Yeah, I forgot to combine those files after the update. They have been readded.

It might be nice to track these sorts of issues on the site repositories.
